@api_key = 
@customer_id = 
@invoice_id = 

### POST request to register a business
POST http://localhost:8080/business
Content-Type: application/json

{
  "name": "star-cafe3",
  "email": "info@starcafe3.in"
}

### POST request to create a customer for a business without authentication
POST http://localhost:8080/customer
Content-Type: application/json

{
  "name": "axay",
  "email": "axay@gmail.com"
}

### POST request to create a customer for a business with authentication
POST http://localhost:8080/customer
Content-Type: application/json
Authorization: Bearer {{api_key}}

{
  "name": "axay",
  "email": "axay@gmail.com"
}
  
### GET request to fetch customers for a business with authentication
GET http://localhost:8080/customers
Authorization: Bearer {{api_key}}

### GET request to fetch a specific customer for a business with authentication
GET http://localhost:8080/customers/{{customer_id}}
Authorization: Bearer {{api_key}}

### create an invoice for a customer with authentication
POST http://localhost:8080/invoice
Content-Type: application/json
Authorization: Bearer {{api_key}}

{
  "customer_id": "{{customer_id}}",
  "items": [
    {
      "description": "AC3",
      "quantity": 3,
      "unit_amount_cents": 300
    },
    {
      "description": "TV3",
      "quantity": 2,
      "unit_amount_cents": 600
    }
  ]
}

### GET request to fetch a specific invoice with authentication
GET http://localhost:8080/invoice/{{invoice_id}}
Content-Type: application/json
Authorization: Bearer {{api_key}}

### GET request to invoices with a status filter for a business with authentication
GET http://localhost:8080/invoices?status=open
Content-Type: application/json
Authorization: Bearer {{api_key}}

### GET request to  fetch all the invoices for a business with authentication
GET http://localhost:8080/invoices
Content-Type: application/json
Authorization: Bearer {{api_key}}

### POST request to pay an invoice with a card token tok_network_error
POST http://localhost:8080/invoices/{{invoice_id}}/pay
Content-Type: application/json
Authorization: Bearer {{api_key}}

{
  "card_token": "tok_network_error",
  "idempotency_key": "unique_key_126"
}

### POST request to pay an invoice with a card token tok_timeout
POST http://localhost:8080/invoices/{{invoice_id}}/pay
Content-Type: application/json
Authorization: Bearer {{api_key}}

{
  "card_token": "tok_timeout",
  "idempotency_key": "unique_key_128"
}

### POST request to pay an invoice with a card token tok_card_declined
POST http://localhost:8080/invoices/{{invoice_id}}/pay
Content-Type: application/json
Authorization: Bearer {{api_key}}

{
  "card_token": "tok_card_declined",
  "idempotency_key": "unique_key_127"
}

### POST request to pay an invoice with a card token tok_success
POST http://localhost:8080/invoices/{{invoice_id}}/pay
Content-Type: application/json
Authorization: Bearer {{api_key}}

{
  "card_token": "tok_success",
  "idempotency_key": "unique_key_125"
}